# This is an example .gitlab-ci.yml file for a project hosted on GitLab

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run dev
test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying..."

  only:
    - main # Deploy only when changes are pushed to the main branch
